notifications:
  email:
    recipients:
      - zhdanoff.alexey@gmail.com
    on_success: never
    on_failure: never

language: rust

rust:
    - nightly
install:
    - cd rust_hedera_sdk/
    - cargo build
