[package]
name = "simple_sample"
version = "0.1.0"
authors = ["Dmitry <45120847+D1mk4Novikov@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.3.0"
wasm-bindgen = "0.2.40"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]